# Generated by Django 4.2 on 2026-06-24 00:33

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionERP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=200, verbose_name='Nombre de la empresa')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('moneda', models.CharField(default='MXN', help_text='Ejemplos: MXN, USD, EUR', max_length=3, verbose_name='Moneda (ISO 4217)')),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=Decimal('16.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='IVA (%)')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracion/', verbose_name='Logo de la empresa')),
            ],
            options={
                'verbose_name': 'Configuración ERP',
                'verbose_name_plural': 'Configuración ERP',
            },
        ),
    ]
